# Generated by Django 3.0.3 on 2020-09-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metabolites',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('smiles', models.TextField(blank=True, null=True)),
                ('inchikey', models.CharField(blank=True, max_length=27, null=True)),
                ('compartment', models.CharField(blank=True, max_length=5, null=True)),
                ('charge', models.IntegerField(blank=True, null=True)),
                ('mnxm', models.CharField(blank=True, max_length=30, null=True)),
                ('chebi', models.CharField(blank=True, max_length=30, null=True)),
                ('bigg', models.CharField(blank=True, max_length=30, null=True)),
                ('biocyc', models.CharField(blank=True, max_length=30, null=True)),
                ('kegg', models.CharField(blank=True, max_length=30, null=True)),
                ('hmbd', models.CharField(blank=True, max_length=30, null=True)),
                ('sabiork', models.CharField(blank=True, max_length=30, null=True)),
                ('sbo', models.CharField(blank=True, max_length=30, null=True)),
                ('seed', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('subsystem', models.CharField(blank=True, max_length=255, null=True)),
                ('ec_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mnxr', models.CharField(blank=True, max_length=50, null=True)),
                ('seed', models.CharField(blank=True, max_length=50, null=True)),
                ('bigg', models.CharField(blank=True, max_length=50, null=True)),
                ('biocyc', models.CharField(blank=True, max_length=50, null=True)),
                ('kegg', models.CharField(blank=True, max_length=50, null=True)),
                ('rhea', models.CharField(blank=True, max_length=50, null=True)),
                ('sbo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reaction_substrates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stochiometry', models.IntegerField()),
                ('metabolite_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelisation.Metabolites')),
                ('reaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelisation.Reactions')),
            ],
        ),
    ]
