# Generated by Django 3.0.3 on 2020-09-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='substrates',
            field=models.ManyToManyField(related_name='substrates', through='modelisation.Reaction_substrates', to='modelisation.Metabolites'),
        ),
        migrations.CreateModel(
            name='Reaction_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stochiometry', models.IntegerField()),
                ('metabolite_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelisation.Metabolites')),
                ('reaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelisation.Reactions')),
            ],
        ),
        migrations.AddField(
            model_name='reactions',
            name='products',
            field=models.ManyToManyField(related_name='products', through='modelisation.Reaction_products', to='modelisation.Metabolites'),
        ),
    ]
