# Generated by Django 3.0.3 on 2020-09-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelisation', '0002_auto_20200910_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction_products',
            unique_together={('reaction_id', 'metabolite_id')},
        ),
    ]
