# Generated by Django 3.0.3 on 2020-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelisation', '0005_auto_20200912_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='GSModels',
        ),
        migrations.AddField(
            model_name='reactions',
            name='models',
            field=models.ManyToManyField(related_name='models', through='modelisation.Reaction_model', to='modelisation.GSModels'),
        ),
    ]
