# Generated by Django 3.0.3 on 2020-09-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelisation', '0007_auto_20200913_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metabolites',
            old_name='hmbd',
            new_name='hmdb',
        ),
        migrations.RenameField(
            model_name='metabolites',
            old_name='kegg',
            new_name='kegg_compound',
        ),
        migrations.AddField(
            model_name='metabolites',
            name='kegg_drug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
