# Generated by Django 3.0.3 on 2020-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelisation', '0009_auto_20200913_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='metabolites',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
